language: perl

sudo: false

perl:
    - "5.26"

env:
  - BLASTVER=2.9.0

install:
    - "cpanm --quiet --notest Bio::Perl"
    - "wget http://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/${BLASTVER}/ncbi-blast-${BLASTVER}+-x64-linux.tar.gz"
    - "tar zxvf ncbi-blast-${BLASTVER}+-x64-linux.tar.gz"
    - "export PATH=$PWD/bin:$PWD/ncbi-blast-${BLASTVER}+/bin:$PATH"

script:
    - "berokka --version"
    - "berokka --help"
    - "! berokka --doesnotexist"
    - "berokka --check"
    - "berokka --test"
